apitoken:
channel: '#newfriends'
redditusername:
redditpassword:
tier1:
    -Looking to join
    -group of friends
    -new person
tier2:
    -joining
    -settlement
    -large city
    -small city
    -large town
    -small town
    -start
