apitoken: 
channel: '#newfriends'
redditusername: 
redditpassword:
sheetkey: 
tier1:
    -looking
    -join
    -new
    -starting
    -server
tier2:
    -joining
    -settlement
    -large city
    -small city
    -large town
    -small town
    -start
